/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Al
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form framePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addRuta = new javax.swing.JMenuItem();
        getRuta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addPilot = new javax.swing.JMenuItem();
        getPilot = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addProveedor = new javax.swing.JMenuItem();
        getProveedor = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        addClient = new javax.swing.JMenuItem();
        getClient = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        getReport = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alimentamos S.A");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jMenu1.setText("Rutas");

        addRuta.setText("Añadir Ruta");
        jMenu1.add(addRuta);

        getRuta.setText("Consultar Ruta");
        jMenu1.add(getRuta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Conductores");

        addPilot.setText("Añadir Conductor");
        jMenu2.add(addPilot);

        getPilot.setText("Consultar Conductor");
        jMenu2.add(getPilot);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Proveedores");

        addProveedor.setText("Añadir Proveedor");
        jMenu3.add(addProveedor);

        getProveedor.setText("Consultar Proveedor");
        jMenu3.add(getProveedor);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Clientes");

        addClient.setText("Añadir Cliente");
        jMenu6.add(addClient);

        getClient.setText("Consultar Cliente");
        jMenu6.add(getClient);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Reportes");

        getReport.setText("Generar Reporte");
        jMenu5.add(getReport);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JMenuItem getAddClient() {
        return addClient;
    }

    public void setAddClient(JMenuItem addClient) {
        this.addClient = addClient;
    }

    public JMenuItem getAddPilot() {
        return addPilot;
    }

    public void setAddPilot(JMenuItem addPilot) {
        this.addPilot = addPilot;
    }

    public JMenuItem getAddProveedor() {
        return addProveedor;
    }

    public void setAddProveedor(JMenuItem addProveedor) {
        this.addProveedor = addProveedor;
    }

    public JMenuItem getAddRuta() {
        return addRuta;
    }

    public void setAddRuta(JMenuItem addRuta) {
        this.addRuta = addRuta;
    }

    public JMenuItem getGetClient() {
        return getClient;
    }

    public void setGetClient(JMenuItem getClient) {
        this.getClient = getClient;
    }

    public JMenuItem getGetPilot() {
        return getPilot;
    }

    public void setGetPilot(JMenuItem getPilot) {
        this.getPilot = getPilot;
    }

    public JMenuItem getGetProveedor() {
        return getProveedor;
    }

    public void setGetProveedor(JMenuItem getProveedor) {
        this.getProveedor = getProveedor;
    }

    public JMenuItem getGetReport() {
        return getReport;
    }

    public void setGetReport(JMenuItem getReport) {
        this.getReport = getReport;
    }

    public JMenuItem getGetRuta() {
        return getRuta;
    }

    public void setGetRuta(JMenuItem getRuta) {
        this.getRuta = getRuta;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenu getjMenu4() {
        return jMenu4;
    }

    public void setjMenu4(JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    public JMenu getjMenu5() {
        return jMenu5;
    }

    public void setjMenu5(JMenu jMenu5) {
        this.jMenu5 = jMenu5;
    }

    public JMenu getjMenu6() {
        return jMenu6;
    }

    public void setjMenu6(JMenu jMenu6) {
        this.jMenu6 = jMenu6;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     * @param args the command line arguments
     */
    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addClient;
    private javax.swing.JMenuItem addPilot;
    private javax.swing.JMenuItem addProveedor;
    private javax.swing.JMenuItem addRuta;
    private javax.swing.JMenuItem getClient;
    private javax.swing.JMenuItem getPilot;
    private javax.swing.JMenuItem getProveedor;
    private javax.swing.JMenuItem getReport;
    private javax.swing.JMenuItem getRuta;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
